---
- name: Install zsh
  become: true
  ansible.builtin.package:
    name: zsh
    state: present

- name: Set user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ omz_user }}"
    shell: /bin/zsh

- name: Clone Oh My Zsh
  ansible.builtin.git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "/home/{{ omz_user }}/.oh-my-zsh"
    depth: 1

- name: Clone zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "/home/{{ omz_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1

- name: Clone zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: "/home/{{ omz_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1

- name: Create zshrc from template
  ansible.builtin.template:
    src: zshrc.j2
    dest: "/home/{{ omz_user }}/.zshrc"
    backup: true
