---
- name: Configure local workstation
  hosts: localhost
  roles:
    - ../roles/neovim

    - role: ../roles/oh-my-zsh
      when: ansible_system == 'Linux'
    - role: ../roles/starship
      when: ansible_system == 'Windows'
    - role: ../roles/win-dev-env
      when: ansible_system == 'Windows'
