---
# site.yml: Main playbook for workstation configuration
# Usage:
#   Standard: ansible-playbook -i inventory/hosts.yml playbooks/site.yml
#   Windows Activation: Add --tags windows_activation

- name: Configure cross-platform components
  hosts: localhost
  roles:
    - neovim

- name: Configure Linux environment
  hosts: localhost
  roles:
    - role: linux-apps
      when: ansible_system == 'Linux'
    - role: oh-my-zsh
      when: ansible_system == 'Linux'

- name: Configure Windows environment
  hosts: localhost
  roles:
    - role: win-apps
      when: ansible_system == 'Windows'
    - role: starship
      when: ansible_system == 'Windows'
    - role: win-dev-env
      when: ansible_system == 'Windows'

- name: Windows Activation (Optional)
  hosts: localhost
  roles:
    - role: activate-win
      when: ansible_system == 'Windows' and enable_windows_activation | default(false) | bool
  tags:
    - never
    - windows_activation
