---
# dnf software provisioning

- name: Update package cache
  become: true
  dnf:
    update_cache: yes

- name: Define application groups
  set_fact:
    dev_tools:
      - git
      - neovim
      - vim
      - tmux
      - cmake
      - gcc
      - g++
      - clang
      - python3-pip
      - nodejs
      - npm
      - doxygen
      - ripgrep
      - rust
      - cargo
      - fzf
      - radare2
      - zathura
    tex_tools:
      - texlive-scheme-basic
      - texlive-latex
      - texlive-collection-latexextra
    system_utils:
      - gnome-tweaks
      - timeshift
      - flameshot
      - copyq
      - flatpak
    media_apps:
      - vlc
      - mpv
      - obs-studio
    office_productivity:
      - libreoffice
      - gimp
      - inkscape
      - shotwell
    browsers:
      - chromium
    terminals:
      - alacritty

- name: Install developer tools
  become: true
  dnf:
    name: "{{ dev_tools }}"
    state: present
  register: dev_install

- name: Install LaTeX tools
  become: true
  dnf:
    name: "{{ tex_tools }}"
    state: present
  register: tex_install

- name: Install system utilities
  become: true
  dnf:
    name: "{{ system_utils }}"
    state: present
  register: sys_install

- name: Install media applications
  become: true
  dnf:
    name: "{{ media_apps }}"
    state: present
  register: media_install

- name: Install office and productivity applications
  become: true
  dnf:
    name: "{{ office_productivity }}"
    state: present
  register: office_install

- name: Install browsers
  become: true
  dnf:
    name: "{{ browsers }}"
    state: present
  register: browser_install

- name: Install terminal emulators
  become: true
  dnf:
    name: "{{ terminals }}"
    state: present
  register: terminal_install

- name: Enable Flathub repository
  become: true
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  changed_when: false

- name: Install Flatpak applications
  become: true
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - com.discordapp.Discord
    - com.obsidian.Obsidian
    - ru.yandex.Browser
    - org.telegram.desktop
    - org.ghidra_sre.Ghidra
  register: flatpak_install
