name: Ansible Syntax Check

on:
  push:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
  pull_request:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"

jobs:
  syntax-check:
    name: Ansible Syntax Validation
    runs-on: ubuntu-latest
    container:
      image: cytopia/ansible:latest-tools
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Syntax check playbooks
        run: |
          find playbooks -type f -name "*.yml" | xargs -I{} ansible-playbook --syntax-check {}

      - name: Syntax check inventory
        run: |
          ansible-inventory --graph -i inventory/hosts.yml

      - name: Dry run
        run: |
          ansible-playbook -i inventory/hosts.yml playbooks/site.yml --check
