name: Ansible Syntax Check

on:
  push:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
      - ".github/workflows/**/*.yml"
  pull_request:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
      - ".github/workflows/**/*.yml"

jobs:
  syntax-check:
    strategy:
      matrix:
        platform: [linux, windows]
        include:
          - platform: linux
            os: fedora-latest
          - platform: windows
            os: windows-latest

    name: Ansible Syntax Check (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # Linux-specific steps using Docker
      - name: Linux - Syntax check playbooks
        if: matrix.platform == 'linux'
        uses: docker://cytopia/ansible:latest-tools
        with:
          entrypoint: /bin/sh
          args: -c "find playbooks -type f -name \"*.yml\" | xargs -I{} ansible-playbook --syntax-check {}"

      - name: Linux - Syntax check inventory
        if: matrix.platform == 'linux'
        uses: docker://cytopia/ansible:latest-tools
        with:
          entrypoint: ansible-inventory
          args: --graph -i inventory/hosts.yml

      - name: Linux - Dry run
        if: matrix.platform == 'linux'
        uses: docker://cytopia/ansible:latest-tools
        with:
          entrypoint: ansible-playbook
          args: -i inventory/hosts.yml playbooks/site.yml --check

      # Windows-specific setup
      - name: Windows - Set up Python
        if: matrix.platform == 'windows'
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Windows - Install Ansible
        if: matrix.platform == 'windows'
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Windows - Syntax check playbooks
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          $env:LC_ALL = 'C.UTF-8' &&
          $env:PYTHONIOENCODING = 'utf-8' &&
          $env:PYTHONUTF8 = '1' &&

          Get-ChildItem -Path playbooks -Filter *.yml -Recurse | ForEach-Object {
            python -m ansible.cli.playbook --syntax-check $_.FullName
          }

      - name: Windows - Syntax check inventory
        if: matrix.platform == 'windows'
        shell: cmd
        run: |
          ansible-inventory --graph -i inventory/hosts.yml

      - name: Windows - Dry run
        if: matrix.platform == 'windows'
        shell: cmd
        run: |
          ansible-playbook -i inventory/hosts.yml playbooks/site.yml --check
