name: Ansible Syntax Check

on:
  push:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
      - ".github/workflows/**/*.yml"
  pull_request:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
      - ".github/workflows/**/*.yml"

jobs:
  syntax-check:
    strategy:
      matrix:
        platform: [linux]
        include:
          - platform: linux
            os: ubuntu-latest

    name: Ansible Syntax Check (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Linux - Syntax check playbooks
        if: matrix.platform == 'linux'
        uses: docker://cytopia/ansible:latest-tools
        with:
          entrypoint: /bin/sh
          args: -c "find playbooks -type f -name \"*.yml\" | xargs -I{} ansible-playbook --syntax-check {}"

      - name: Linux - Syntax check inventory
        if: matrix.platform == 'linux'
        uses: docker://cytopia/ansible:latest-tools
        with:
          entrypoint: ansible-inventory
          args: --graph -i inventory/hosts.yml
