name: Ansible Windows Syntax Check

on:
  push:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
      - ".github/workflows/**/*.yml"
  pull_request:
    paths:
      - "roles/**/*.yml"
      - "playbooks/**/*.yml"
      - "inventory/**/*.yml"
      - ".github/workflows/**/*.yml"

jobs:
  windows-validation:
    name: Ansible Validation (Windows)
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Validate infrastructure
        shell: pwsh
        run: |
          chcp 65001
          ansible-inventory --graph -i inventory/hosts.yml 
          ansible-playbook -i inventory/hosts.yml playbooks/site.yml --check
